name: CI/CD

on:
  push:
    branches:
      - 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v2
        with:
          cpp-version: '98'

      - name: Build and run tests
        run: |
          cd tests
          make

      - name: Run integration tests
        run: make integration

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge feature branch to deploy'
          branch: deploy